version: "3" 
services:
  db:
    container_name: bare-necessities-db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bare_necessities
    ports:
      - "5432:5432"

  web:
    container_name: bare-necessities-web
    build:
        context: .
    image: mozilla/bare-necessities
    volumes:
      - ./:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db/bare_necessities
      - FLASK_APP=/app/src/web/api.py
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"

  db-migration:
    container_name: bare-necessities-db-migration
    build:
        context: .
    image: mozilla/bare-necessities
    volumes:
      - ./:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db/bare_necessities
      - FLASK_APP=/app/src/web/api.py
      - FLASK_ENV=development
    depends_on:
      - db
    links:
      - db
    command:
      [
        "/opt/wait-for-it.sh",
        "db:5432",
        "--",
        "flask", "db", "upgrade",
      ]